# 图标的存储方式
# 可选值:
#   - 'local': (默认) 将图标保存在本地的持久化数据卷中 (`/app/data/icons`)，
#              并通过本工具直接提供访问。
#   - 'minio': 将图标上传到 MinIO 对象存储中，并通过 MinIO 提供的 URL 直接访问。
icon_storage:
  strategy: "local"

# MinIO 对象存储配置 (仅在 strategy 设置为 'minio' 时生效)
minio:
  endpoint: "http://192.168.1.100:9000" # MinIO 服务地址，http://ip:port 或 https://域名
  access_key: ""
  secret_key: ""
  icons_bucket: "icons" # 图标存储桶
  background_bucket: "background" # 背景图存储桶
  use_ssl: true # 是否使用 SSL 连接

# Docker API 地址，如'http://192.168.1.100:2375'
docker_api_endpoint: "http://192.168.1.100:2375"
